NPM 배포 준비
airman5573/mockpress pull request #8
Opened 2022-10-24 14:07 UTC by airman5573

1. rollup setting : cjs, esm 둘다 지원합니다.
2. d.ts 가 없는 관계로 아직 typescript는 지원하지 않습니다.

2022-10-24 14:31 UTC, uk960214 requested changes
어려운 것들 설정하느라 고생 많으셨습니다!
출시 준비이니 만큼 조금 세세하게 질문과 코멘트 남겼습니다!

2022-10-24 14:31 UTC, uk960214 commented on package.json
> +    "nanoid": "^3.3.4"
👍

2022-10-24 14:31 UTC, uk960214 commented on README.md
> +Let's make mock data easy!
Mock data generator, simple and flexible.

정도로 쓰면 어떨까요?
뭔가 npm 패키지들 보면 용도를 되게 간단하고 한 눈에 들어오게 작성했던데,
이 라이브러리가 쓰기 쉽고 유연하다는 걸 강조하면 좋을 것 같아요!

2022-10-24 14:31 UTC, uk960214 commented on package.json
> +  },
이렇게 export 하면 어떤 일이 발생하나요?
require로 요청할 때는 bundle.cjs가 반환되고 import로 요청할 때는 bundle.mjs가 반환되는 건가요?

2022-10-24 14:31 UTC, uk960214 commented on rollup.config.js
> +      sourcemap: true,
sourcemap을 true로 설정하면 소스맵 파일이 생성되는 것 맞나요? 어디에 사용하나요?

2022-10-24 14:31 UTC, uk960214 commented on src/test.js
> +      name: mock.koreanName(),
어머니 이름은 'female' 인자를 추가하는게 어떨까요?

2022-10-24 14:31 UTC, uk960214 commented on src/test.js
>  const personSchema = {
이 파일의 파일명이 'test.js'이기 때문에 테스트 파일로 오해가 발생할 수 있을 것 같은데,
sample.js나 example.js처럼 오해 소지가 없는 파일명으로 변경하는 건 어떻게 생각하시나요?

2022-10-24 14:31 UTC, uk960214 commented on package.json
>    "version": "1.0.0",
저희가 현재 출시하는 버전이 1.0.0이 적절한 지 논의할 필요가 있어보입니다!

2022-10-24 14:36 UTC, airman5573 commented on README.md
> +Let's make mock data easy!
좋습니다 👍

2022-10-24 14:36 UTC, airman5573 commented on package.json
> +  },
맞아요!

2022-10-24 14:38 UTC, airman5573 commented on rollup.config.js
> +      sourcemap: true,
버그찾을때 유용할것 같아서 설정해 주었습니다.  
production에서 sourcemap 있으면 별로일까요?

2022-10-24 14:38 UTC, airman5573 commented on src/test.js
> +      name: mock.koreanName(),
실수로 지웠군요!  
다시 추가하겠습니다 :D

2022-10-24 14:38 UTC, airman5573 commented on src/test.js
>  const personSchema = {
좋습니다 👍

2022-10-24 14:39 UTC, airman5573 commented on package.json
>    "version": "1.0.0",
음, 맞아요.  
0.1.0 부터 시작해볼까요?

2022-10-24 14:42 UTC, airman5573 commented on package.json
> +  "sideEffects": false,
sideEffects는 tree-shaking이 잘되도록 설정해 준것이 맞습니다.  
유틸함수를 별개의 파일로 분리한것은 tree-shaking이 잘 안되는 환경에서 사용자가 함수를 개별적으로 require해서 사용하도록 하기 위함입니다.  
그리고, 이렇게 나누면 코드를 읽기가 더 쉬워지고, 테스트도 개별 파일로 만들 수 있기 때문에 더 좋다고 생각합니다.

2022-10-24 14:58 UTC, uk960214 commented on package.json
>    "version": "1.0.0",
좋습니다!

2022-10-24 15:00 UTC, uk960214 commented on package.json
> +  "sideEffects": false,
아하 이해했습니다!
또 궁금한 점은 'tree-shaking이 잘 안되는 환경'은 무엇일까요?
이 환경이 사용자의 프로젝트 설정에 의존적인걸까요?

2022-10-24 15:02 UTC, uk960214 commented on rollup.config.js
> +      sourcemap: true,
성능에만 문제가 없다면 딱히 보안 측면에서 난독화가 중요한 패키지는 아니니 있어도 될 것 같아요!
이 옵션으로 인해서 빌드 속도나 실행 속도에 영향이 가지는 않나요?

2022-10-25 00:44 UTC, airman5573 commented on rollup.config.js
> +      sourcemap: true,
네, 아직 저희 코드 양이 적어서 빌드속도에 유의미한 영향을 주지는 않습니다.  
실행속도에는 전혀 영향이 없겠지만, node_modules의 크기가 조금 커진다는 단점이 있습니다.  
우선 써보다가 성능에 영향이 간다고 판단될때 제거를 해봅시다!

2022-10-25 00:50 UTC, airman5573 commented on package.json
> +  "sideEffects": false,
네 맞습니다. 사용자의 번들러에 따라 commonjs 방식의 라이브러리에 대해서 tree-shaking을 잘 안해줄 수 도 있습니다.  

이를테면 webpack4에서는 commonjs 방식의 라이브러리들은 tree-shaking이 잘 안되는 편이었고, webpack5에 와서 조금 나아졌습니다. 반면 rollup에서는 commonjs쪽도 webpack보다는 tree-shaking을 잘 지원하는걸로 알고 있습니다.  

결론적으로, 때에따라서 require('mockpress/utils/date'); 이렇게 해주면 해당 파일만 불러오기 때문에 tree-shaking이 잘 안되는 환경에서 유용할것으로 생각됩니다.

2022-10-25 04:46 UTC, uk960214 approved these changes
궁금한 점 모두 해결했습니다! 수고하셨습니다!

2022-10-25 07:32 UTC, merged