파일 쓰기 기능 추가
airman5573/mockpress pull request #9
Opened 2022-10-25 04:01 UTC by airman5573

```javascript
import { mock, generate, writeFile } from "./src/index.js";

const personSchema = {
  id: mock.autoIncrement(),
  index: (current, loopIndex) => `${loopIndex + 1} 번째 Object`,
  name: mock.koreanName(),
  introduce: (current, loopIndex) =>
    `안녕하세요 제 이름은 ${current.name} 입니다!`,
  parents: {
    mother: {
      name: mock.koreanName(),
    },
  },
  parentIntroduce: (current, loopIndex) =>
    `저희 어머니 성함은 ${current.parents.mother.name} 입니다!`,
  profileImage: mock.image(200, 200),
  age: mock.integer(10, 20),
  address: mock.koreanAddress(),
  hobby: {
    id: mock.autoIncrement(),
    cost: mock.money(1000, 10000, 100),
  },
};

const result = generate(personSchema, 2);

writeFile("./hoho/export.json", result).then(() => {
  console.log("Success!!");
});
```

이렇게 writeFile 함수를 사용해서 data를 json으로 export 할 수 있습니다.

2022-10-25 04:52 UTC, uk960214 requested changes
사실 변경점은 없고 궁금한 질문들이 몇 개 있습니다! 코멘트에 남겨놓았어요!

2022-10-25 04:52 UTC, uk960214 commented on src/writer.js
> +const writeFile = (destinationPath, data, as = AS_JSON) => {
destinationPath에 실제로 생성되는 파일명까지 모두 포함되는 것 같네요?
만약 1. 추후에도 이렇게 하나의 인자로 받을 것이라면 변수명을 바꾸거나 2. 나중에는 파일명을 따로 받을 생각이라면 이렇게 두어도 될 것 같아요!

2022-10-25 04:52 UTC, uk960214 commented on src/writer.js
> +  }
추후에 다른 파일 형식이 추가되면 여기에 다른 분기가 추가되는 것 맞나요?

2022-10-25 04:52 UTC, uk960214 commented on sample.js
> +});
현재로서는 사용자가 직접 이렇게 작성해야만 파일을 생성할 수 있는 것 맞나요?

2022-10-25 07:33 UTC, airman5573 commented on src/writer.js
> +const writeFile = (destinationPath, data, as = AS_JSON) => {
"path" 라는 용어에 filename이 포함되지 않는다는 말씀이신거죠?

2022-10-25 07:34 UTC, airman5573 commented on src/writer.js
> +  }
네, 맞습니다!

2022-10-25 07:35 UTC, airman5573 commented on sample.js
> +});
맞습니다!

2022-10-26 07:05 UTC, uk960214 commented on src/writer.js
> +const writeFile = (destinationPath, data, as = AS_JSON) => {
맞아요! 물론 라이브러리/패키지 마다 config 방식이 다르긴 한데 저는 개인적으로 path와 filename이 분리되는 방식이 더 명료하다고 생각합니다!

2022-10-26 08:35 UTC, airman5573 commented on src/writer.js
> +const writeFile = (destinationPath, data, as = AS_JSON) => {
와 이거 어렵네요.  
우선!  
[linux information](http://www.linfo.org/path.html)에서 정의한 path는  
`A path is the address of an object (i.e., file, directory or link) on a filesystem`  
이라고 나와있습니다.  

반면!  
webpack에는
```javascript
output: {
    filename: '[name]-[contenthash].js',
    path: join(__dirname, '../dist'),
    publicPath: '/',
},
```
이렇게 구분되어 있네요.  
위를보니 filename과 path를 분리하는 편이 좋을것 같네요.

2022-10-26 13:17 UTC, uk960214 commented on src/writer.js
> +const writeFile = (destinationPath, data, as = AS_JSON) => {
제가 단순히 생각했던 것 보다 훨씬 다양할 수도 있겠군요! 의견 반영해주셔서 감사합니다!!

2022-10-26 13:18 UTC, uk960214 approved these changes
수고 많으셨습니다!

2022-10-27 14:42 UTC, merged